apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  annotations:
    gke.io/cluster: "bootstrap://"
  name: default-pool
  namespace: "PROJECT" # kpt-set: ${gcloud.core.project}
spec:
  initialNodeCount: 2
  autoscaling:
    minNodeCount: 2
    maxNodeCount: 4 # kpt-set: ${gcloud.container.nodepool.max-nodes}
  nodeConfig:
    machineType: e2-standard-4
    workloadMetadataConfig:
      nodeMetadata: GKE_METADATA_SERVER
  management:
    autoRepair: true
    autoUpgrade: true
  clusterRef:
    name: "asm-cluster" # kpt-set: ${gcloud.container.cluster}
